var countrywisedata2 = (function() {
    var countrywisedata2 = null;
    jQuery.ajax({
        'async': false,
        'global': false,
        'dataType': 'json',
        'url': 'https://thefederal.com/api/scraper.php?m=Corona&t=totalCases',
        'success': function(data) {
            countrywisedata2 = data;
            //   console.log("DATA:"+JSON.stringify(data, null, 4));
            //console.log("DATA:"+data);
        }
    });
    return countrywisedata2;
})();

var countrywisedata = [
    {
      "countryId": "156",
      "Country": "China",
      "Total Cases": "80814",
      "New Cases": "+21",
      "Total Deaths": "3177",
      "New Deaths": "+8",
      "Total Recovered": "64119",
      "Active Cases": "13518",
      "Serious": "4020",
      "Total cases 1M": "56.1"
    },
    {
      "countryId": "380",
      "Country": "Italy",
      "Total Cases": "15113",
      "New Cases": "NULL",
      "Total Deaths": "1016",
      "New Deaths": "NULL",
      "Total Recovered": "1258",
      "Active Cases": "12839",
      "Serious": "1153",
      "Total cases 1M": "250.0"
    },
    {
      "countryId": "364",
      "Country": "Iran",
      "Total Cases": "10075",
      "New Cases": "NULL",
      "Total Deaths": "429",
      "New Deaths": "NULL",
      "Total Recovered": "3276",
      "Active Cases": "6370",
      "Serious": "NULL",
      "Total cases 1M": "120.0"
    },
    {
      "countryId": "410",
      "Country": "S. Korea",
      "Total Cases": "7979",
      "New Cases": "+110",
      "Total Deaths": "67",
      "New Deaths": "+1",
      "Total Recovered": "510",
      "Active Cases": "7402",
      "Serious": "93",
      "Total cases 1M": "155.6"
    },
    {
      "countryId": "724",
      "Country": "Spain",
      "Total Cases": "3146",
      "New Cases": "NULL",
      "Total Deaths": "86",
      "New Deaths": "NULL",
      "Total Recovered": "189",
      "Active Cases": "2871",
      "Serious": "190",
      "Total cases 1M": "67.3"
    },
    {
      "countryId": "250",
      "Country": "France",
      "Total Cases": "2876",
      "New Cases": "NULL",
      "Total Deaths": "61",
      "New Deaths": "NULL",
      "Total Recovered": "12",
      "Active Cases": "2803",
      "Serious": "129",
      "Total cases 1M": "44.1"
    },
    {
      "countryId": "276",
      "Country": "Germany",
      "Total Cases": "2745",
      "New Cases": "NULL",
      "Total Deaths": "6",
      "New Deaths": "NULL",
      "Total Recovered": "25",
      "Active Cases": "2714",
      "Serious": "9",
      "Total cases 1M": "32.8"
    },
    {
      "countryId": "840",
      "Country": "USA",
      "Total Cases": "1762",
      "New Cases": "+65",
      "Total Deaths": "41",
      "New Deaths": "NULL",
      "Total Recovered": "31",
      "Active Cases": "1690",
      "Serious": "10",
      "Total cases 1M": "5.3"
    },
    {
      "countryId": "756",
      "Country": "Switzerland",
      "Total Cases": "868",
      "New Cases": "NULL",
      "Total Deaths": "7",
      "New Deaths": "NULL",
      "Total Recovered": "4",
      "Active Cases": "857",
      "Serious": "NULL",
      "Total cases 1M": "100.3"
    },
    {
      "countryId": "578",
      "Country": "Norway",
      "Total Cases": "800",
      "New Cases": "NULL",
      "Total Deaths": "1",
      "New Deaths": "NULL",
      "Total Recovered": "1",
      "Active Cases": "798",
      "Serious": "NULL",
      "Total cases 1M": "147.6"
    },
    {
      "countryId": "NULL",
      "Country": "NULL",
      "Total Cases": "696",
      "New Cases": "NULL",
      "Total Deaths": "7",
      "New Deaths": "NULL",
      "Total Recovered": "325",
      "Active Cases": "364",
      "Serious": "32",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "392",
      "Country": "Japan",
      "Total Cases": "691",
      "New Cases": "NULL",
      "Total Deaths": "19",
      "New Deaths": "NULL",
      "Total Recovered": "118",
      "Active Cases": "554",
      "Serious": "29",
      "Total cases 1M": "5.5"
    },
    {
      "countryId": "752",
      "Country": "Sweden",
      "Total Cases": "687",
      "New Cases": "NULL",
      "Total Deaths": "1",
      "New Deaths": "NULL",
      "Total Recovered": "1",
      "Active Cases": "685",
      "Serious": "2",
      "Total cases 1M": "68.0"
    },
    {
      "countryId": "208",
      "Country": "Denmark",
      "Total Cases": "674",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "1",
      "Active Cases": "673",
      "Serious": "2",
      "Total cases 1M": "116.4"
    },
    {
      "countryId": "528",
      "Country": "Netherlands",
      "Total Cases": "614",
      "New Cases": "NULL",
      "Total Deaths": "5",
      "New Deaths": "NULL",
      "Total Recovered": "2",
      "Active Cases": "607",
      "Serious": "1",
      "Total cases 1M": "35.8"
    },
    {
      "countryId": "826",
      "Country": "UK",
      "Total Cases": "590",
      "New Cases": "NULL",
      "Total Deaths": "10",
      "New Deaths": "NULL",
      "Total Recovered": "18",
      "Active Cases": "562",
      "Serious": "20",
      "Total cases 1M": "8.7"
    },
    {
      "countryId": "56",
      "Country": "Belgium",
      "Total Cases": "399",
      "New Cases": "NULL",
      "Total Deaths": "3",
      "New Deaths": "NULL",
      "Total Recovered": "1",
      "Active Cases": "395",
      "Serious": "2",
      "Total cases 1M": "34.4"
    },
    {
      "countryId": "40",
      "Country": "Austria",
      "Total Cases": "361",
      "New Cases": "NULL",
      "Total Deaths": "1",
      "New Deaths": "NULL",
      "Total Recovered": "4",
      "Active Cases": "356",
      "Serious": "1",
      "Total cases 1M": "40.1"
    },
    {
      "countryId": "634",
      "Country": "Qatar",
      "Total Cases": "262",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "262",
      "Serious": "NULL",
      "Total cases 1M": "90.9"
    },
    {
      "countryId": "48",
      "Country": "Bahrain",
      "Total Cases": "197",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "35",
      "Active Cases": "162",
      "Serious": "1",
      "Total cases 1M": "115.8"
    },
    {
      "countryId": "702",
      "Country": "Singapore",
      "Total Cases": "187",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "96",
      "Active Cases": "91",
      "Serious": "12",
      "Total cases 1M": "32.0"
    },
    {
      "countryId": "36",
      "Country": "Australia",
      "Total Cases": "160",
      "New Cases": "+4",
      "Total Deaths": "3",
      "New Deaths": "NULL",
      "Total Recovered": "26",
      "Active Cases": "131",
      "Serious": "1",
      "Total cases 1M": "6.3"
    },
    {
      "countryId": "124",
      "Country": "Canada",
      "Total Cases": "158",
      "New Cases": "+16",
      "Total Deaths": "1",
      "New Deaths": "NULL",
      "Total Recovered": "11",
      "Active Cases": "146",
      "Serious": "1",
      "Total cases 1M": "4.2"
    },
    {
      "countryId": "458",
      "Country": "Malaysia",
      "Total Cases": "158",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "32",
      "Active Cases": "126",
      "Serious": "3",
      "Total cases 1M": "4.9"
    },
    {
      "countryId": "NULL",
      "Country": "NULL",
      "Total Cases": "132",
      "New Cases": "+1",
      "Total Deaths": "4",
      "New Deaths": "+1",
      "Total Recovered": "77",
      "Active Cases": "51",
      "Serious": "4",
      "Total cases 1M": "17.6"
    },
    {
      "countryId": "300",
      "Country": "Greece",
      "Total Cases": "117",
      "New Cases": "NULL",
      "Total Deaths": "1",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "116",
      "Serious": "2",
      "Total cases 1M": "11.2"
    },
    {
      "countryId": "352",
      "Country": "Iceland",
      "Total Cases": "117",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "117",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "NULL",
      "Country": "NULL",
      "Total Cases": "116",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "116",
      "Serious": "2",
      "Total cases 1M": "10.8"
    },
    {
      "countryId": "246",
      "Country": "Finland",
      "Total Cases": "109",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "1",
      "Active Cases": "108",
      "Serious": "NULL",
      "Total cases 1M": "19.7"
    },
    {
      "countryId": "376",
      "Country": "Israel",
      "Total Cases": "109",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "4",
      "Active Cases": "105",
      "Serious": "2",
      "Total cases 1M": "12.6"
    },
    {
      "countryId": "705",
      "Country": "Slovenia",
      "Total Cases": "96",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "96",
      "Serious": "NULL",
      "Total cases 1M": "46.2"
    },
    {
      "countryId": "784",
      "Country": "UAE",
      "Total Cases": "85",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "20",
      "Active Cases": "65",
      "Serious": "2",
      "Total cases 1M": "8.6"
    },
    {
      "countryId": "368",
      "Country": "Iraq",
      "Total Cases": "83",
      "New Cases": "NULL",
      "Total Deaths": "8",
      "New Deaths": "NULL",
      "Total Recovered": "24",
      "Active Cases": "51",
      "Serious": "NULL",
      "Total cases 1M": "2.1"
    },
    {
      "countryId": "818",
      "Country": "Egypt",
      "Total Cases": "80",
      "New Cases": "NULL",
      "Total Deaths": "2",
      "New Deaths": "NULL",
      "Total Recovered": "27",
      "Active Cases": "51",
      "Serious": "NULL",
      "Total cases 1M": "0.8"
    },
    {
      "countryId": "414",
      "Country": "Kuwait",
      "Total Cases": "80",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "5",
      "Active Cases": "75",
      "Serious": "4",
      "Total cases 1M": "18.7"
    },
    {
      "countryId": "620",
      "Country": "Portugal",
      "Total Cases": "78",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "1",
      "Active Cases": "77",
      "Serious": "1",
      "Total cases 1M": "7.6"
    },
    {
      "countryId": "76",
      "Country": "Brazil",
      "Total Cases": "77",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "77",
      "Serious": "2",
      "Total cases 1M": "0.4"
    },
    {
      "countryId": "356",
      "Country": "India",
      "Total Cases": "75",
      "New Cases": "+1",
      "Total Deaths": "1",
      "New Deaths": "NULL",
      "Total Recovered": "4",
      "Active Cases": "70",
      "Serious": "NULL",
      "Total cases 1M": "0.1"
    },
    {
      "countryId": "674",
      "Country": "San Marino",
      "Total Cases": "72",
      "New Cases": "NULL",
      "Total Deaths": "5",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "67",
      "Serious": "3",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "372",
      "Country": "Ireland",
      "Total Cases": "70",
      "New Cases": "NULL",
      "Total Deaths": "1",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "69",
      "Serious": "6",
      "Total cases 1M": "14.2"
    },
    {
      "countryId": "764",
      "Country": "Thailand",
      "Total Cases": "70",
      "New Cases": "NULL",
      "Total Deaths": "1",
      "New Deaths": "NULL",
      "Total Recovered": "35",
      "Active Cases": "34",
      "Serious": "1",
      "Total cases 1M": "1.0"
    },
    {
      "countryId": "422",
      "Country": "Lebanon",
      "Total Cases": "68",
      "New Cases": "NULL",
      "Total Deaths": "3",
      "New Deaths": "NULL",
      "Total Recovered": "1",
      "Active Cases": "64",
      "Serious": "3",
      "Total cases 1M": "10.0"
    },
    {
      "countryId": "682",
      "Country": "Saudi Arabia",
      "Total Cases": "62",
      "New Cases": "+17",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "1",
      "Active Cases": "61",
      "Serious": "NULL",
      "Total cases 1M": "1.8"
    },
    {
      "countryId": "642",
      "Country": "Romania",
      "Total Cases": "59",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "7",
      "Active Cases": "52",
      "Serious": "1",
      "Total cases 1M": "3.1"
    },
    {
      "countryId": "608",
      "Country": "Philippines",
      "Total Cases": "52",
      "New Cases": "NULL",
      "Total Deaths": "5",
      "New Deaths": "NULL",
      "Total Recovered": "2",
      "Active Cases": "45",
      "Serious": "1",
      "Total cases 1M": "0.5"
    },
    {
      "countryId": "616",
      "Country": "Poland",
      "Total Cases": "51",
      "New Cases": "NULL",
      "Total Deaths": "1",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "50",
      "Serious": "3",
      "Total cases 1M": "1.3"
    },
    {
      "countryId": "158",
      "Country": "Taiwan",
      "Total Cases": "49",
      "New Cases": "NULL",
      "Total Deaths": "1",
      "New Deaths": "NULL",
      "Total Recovered": "20",
      "Active Cases": "28",
      "Serious": "NULL",
      "Total cases 1M": "2.1"
    },
    {
      "countryId": "704",
      "Country": "Vietnam",
      "Total Cases": "44",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "16",
      "Active Cases": "28",
      "Serious": "NULL",
      "Total cases 1M": "0.5"
    },
    {
      "countryId": "360",
      "Country": "Indonesia",
      "Total Cases": "34",
      "New Cases": "NULL",
      "Total Deaths": "1",
      "New Deaths": "NULL",
      "Total Recovered": "3",
      "Active Cases": "30",
      "Serious": "NULL",
      "Total cases 1M": "0.1"
    },
    {
      "countryId": "643",
      "Country": "Russia",
      "Total Cases": "34",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "3",
      "Active Cases": "31",
      "Serious": "NULL",
      "Total cases 1M": "0.2"
    },
    {
      "countryId": "152",
      "Country": "Chile",
      "Total Cases": "33",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "33",
      "Serious": "NULL",
      "Total cases 1M": "1.7"
    },
    {
      "countryId": "32",
      "Country": "Argentina",
      "Total Cases": "31",
      "New Cases": "NULL",
      "Total Deaths": "1",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "30",
      "Serious": "1",
      "Total cases 1M": "0.7"
    },
    {
      "countryId": "275",
      "Country": "Palestine",
      "Total Cases": "31",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "31",
      "Serious": "NULL",
      "Total cases 1M": "6.1"
    },
    {
      "countryId": "591",
      "Country": "Panama",
      "Total Cases": "27",
      "New Cases": "+13",
      "Total Deaths": "1",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "26",
      "Serious": "NULL",
      "Total cases 1M": "6.3"
    },
    {
      "countryId": "191",
      "Country": "Croatia",
      "Total Cases": "27",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "1",
      "Active Cases": "26",
      "Serious": "NULL",
      "Total cases 1M": "6.6"
    },
    {
      "countryId": "233",
      "Country": "Estonia",
      "Total Cases": "27",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "27",
      "Serious": "NULL",
      "Total cases 1M": "20.4"
    },
    {
      "countryId": "12",
      "Country": "Algeria",
      "Total Cases": "26",
      "New Cases": "NULL",
      "Total Deaths": "2",
      "New Deaths": "NULL",
      "Total Recovered": "10",
      "Active Cases": "14",
      "Serious": "NULL",
      "Total cases 1M": "0.6"
    },
    {
      "countryId": "440",
      "Country": "Luxembourg",
      "Total Cases": "26",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "26",
      "Serious": "1",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "268",
      "Country": "Georgia",
      "Total Cases": "25",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "25",
      "Serious": "1",
      "Total cases 1M": "6.3"
    },
    {
      "countryId": "96",
      "Country": "Brunei",
      "Total Cases": "25",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "25",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "688",
      "Country": "Serbia",
      "Total Cases": "24",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "24",
      "Serious": "NULL",
      "Total cases 1M": "2.7"
    },
    {
      "countryId": "8",
      "Country": "Albania",
      "Total Cases": "23",
      "New Cases": "NULL",
      "Total Deaths": "1",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "22",
      "Serious": "NULL",
      "Total cases 1M": "8.0"
    },
    {
      "countryId": "100",
      "Country": "Bulgaria",
      "Total Cases": "23",
      "New Cases": "NULL",
      "Total Deaths": "1",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "22",
      "Serious": "NULL",
      "Total cases 1M": "3.3"
    },
    {
      "countryId": "188",
      "Country": "Costa Rica",
      "Total Cases": "23",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "23",
      "Serious": "1",
      "Total cases 1M": "4.5"
    },
    {
      "countryId": "604",
      "Country": "Peru",
      "Total Cases": "22",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "22",
      "Serious": "NULL",
      "Total cases 1M": "0.7"
    },
    {
      "countryId": "112",
      "Country": "Belarus",
      "Total Cases": "21",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "3",
      "Active Cases": "18",
      "Serious": "NULL",
      "Total cases 1M": "2.2"
    },
    {
      "countryId": "586",
      "Country": "Pakistan",
      "Total Cases": "21",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "2",
      "Active Cases": "19",
      "Serious": "NULL",
      "Total cases 1M": "0.1"
    },
    {
      "countryId": "703",
      "Country": "Slovakia",
      "Total Cases": "21",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "21",
      "Serious": "NULL",
      "Total cases 1M": "3.8"
    },
    {
      "countryId": "218",
      "Country": "Ecuador",
      "Total Cases": "19",
      "New Cases": "+2",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "19",
      "Serious": "1",
      "Total cases 1M": "1.1"
    },
    {
      "countryId": "512",
      "Country": "Oman",
      "Total Cases": "18",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "9",
      "Active Cases": "9",
      "Serious": "NULL",
      "Total cases 1M": "3.5"
    },
    {
      "countryId": "442",
      "Country": "Latvia",
      "Total Cases": "16",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "1",
      "Active Cases": "15",
      "Serious": "NULL",
      "Total cases 1M": "8.5"
    },
    {
      "countryId": "348",
      "Country": "Hungary",
      "Total Cases": "16",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "16",
      "Serious": "NULL",
      "Total cases 1M": "1.7"
    },
    {
      "countryId": "710",
      "Country": "South Africa",
      "Total Cases": "16",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "16",
      "Serious": "NULL",
      "Total cases 1M": "0.3"
    },
    {
      "countryId": "31",
      "Country": "Azerbaijan",
      "Total Cases": "15",
      "New Cases": "NULL",
      "Total Deaths": "1",
      "New Deaths": "NULL",
      "Total Recovered": "3",
      "Active Cases": "11",
      "Serious": "NULL",
      "Total cases 1M": "1.5"
    },
    {
      "countryId": "788",
      "Country": "Tunisia",
      "Total Cases": "13",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "13",
      "Serious": "2",
      "Total cases 1M": "1.1"
    },
    {
      "countryId": "484",
      "Country": "Mexico",
      "Total Cases": "12",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "4",
      "Active Cases": "8",
      "Serious": "1",
      "Total cases 1M": "0.1"
    },
    {
      "countryId": "70",
      "Country": "Bosnia and Herzegovina",
      "Total Cases": "11",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "11",
      "Serious": "NULL",
      "Total cases 1M": "3.4"
    },
    {
      "countryId": "NULL",
      "Country": "NULL",
      "Total Cases": "10",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "10",
      "Active Cases": "0",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "686",
      "Country": "Senegal",
      "Total Cases": "10",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "1",
      "Active Cases": "9",
      "Serious": "NULL",
      "Total cases 1M": "0.6"
    },
    {
      "countryId": "196",
      "Country": "Cyprus",
      "Total Cases": "10",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "10",
      "Serious": "NULL",
      "Total cases 1M": "8.3"
    },
    {
      "countryId": "807",
      "Country": "North Macedonia",
      "Total Cases": "9",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "1",
      "Active Cases": "8",
      "Serious": "NULL",
      "Total cases 1M": "4.3"
    },
    {
      "countryId": "170",
      "Country": "Colombia",
      "Total Cases": "9",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "9",
      "Serious": "NULL",
      "Total cases 1M": "0.2"
    },
    {
      "countryId": "470",
      "Country": "Malta",
      "Total Cases": "9",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "9",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "462",
      "Country": "Maldives",
      "Total Cases": "8",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "8",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "4",
      "Country": "Afghanistan",
      "Total Cases": "7",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "7",
      "Serious": "NULL",
      "Total cases 1M": "0.2"
    },
    {
      "countryId": "428",
      "Country": "Morocco",
      "Total Cases": "6",
      "New Cases": "NULL",
      "Total Deaths": "1",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "5",
      "Serious": "1",
      "Total cases 1M": "0.2"
    },
    {
      "countryId": "51",
      "Country": "Armenia",
      "Total Cases": "6",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "6",
      "Serious": "NULL",
      "Total cases 1M": "2.0"
    },
    {
      "countryId": "NULL",
      "Country": "French Guiana",
      "Total Cases": "6",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "6",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "498",
      "Country": "Moldova",
      "Total Cases": "6",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "6",
      "Serious": "NULL",
      "Total cases 1M": "1.5"
    },
    {
      "countryId": "600",
      "Country": "Paraguay",
      "Total Cases": "6",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "6",
      "Serious": "1",
      "Total cases 1M": "0.8"
    },
    {
      "countryId": "116",
      "Country": "Cambodia",
      "Total Cases": "5",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "1",
      "Active Cases": "4",
      "Serious": "NULL",
      "Total cases 1M": "0.3"
    },
    {
      "countryId": "214",
      "Country": "Dominican Republic",
      "Total Cases": "5",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "5",
      "Serious": "NULL",
      "Total cases 1M": "0.5"
    },
    {
      "countryId": "554",
      "Country": "New Zealand",
      "Total Cases": "5",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "5",
      "Serious": "NULL",
      "Total cases 1M": "1.0"
    },
    {
      "countryId": "NULL",
      "Country": "NULL",
      "Total Cases": "4",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "4",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "NULL",
      "Country": "NULL",
      "Total Cases": "4",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "4",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "426",
      "Country": "Lithuania",
      "Total Cases": "3",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "3",
      "Serious": "NULL",
      "Total cases 1M": "1.1"
    },
    {
      "countryId": "144",
      "Country": "Sri Lanka",
      "Total Cases": "3",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "1",
      "Active Cases": "2",
      "Serious": "NULL",
      "Total cases 1M": "0.1"
    },
    {
      "countryId": "804",
      "Country": "Ukraine",
      "Total Cases": "3",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "3",
      "Serious": "NULL",
      "Total cases 1M": "0.1"
    },
    {
      "countryId": "50",
      "Country": "Bangladesh",
      "Total Cases": "3",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "3",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "68",
      "Country": "Bolivia",
      "Total Cases": "3",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "3",
      "Serious": "NULL",
      "Total cases 1M": "0.3"
    },
    {
      "countryId": "NULL",
      "Country": "NULL",
      "Total Cases": "3",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "3",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "192",
      "Country": "Cuba",
      "Total Cases": "3",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "3",
      "Serious": "NULL",
      "Total cases 1M": "0.3"
    },
    {
      "countryId": "NULL",
      "Country": "Martinique",
      "Total Cases": "3",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "3",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "492",
      "Country": "Monaco",
      "Total Cases": "2",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "2",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "566",
      "Country": "Nigeria",
      "Total Cases": "2",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "2",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "854",
      "Country": "Burkina Faso",
      "Total Cases": "2",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "2",
      "Serious": "NULL",
      "Total cases 1M": "0.1"
    },
    {
      "countryId": "120",
      "Country": "Cameroon",
      "Total Cases": "2",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "2",
      "Serious": "NULL",
      "Total cases 1M": "0.1"
    },
    {
      "countryId": "234",
      "Country": "Faeroe Islands",
      "Total Cases": "2",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "2",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "288",
      "Country": "Ghana",
      "Total Cases": "2",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "2",
      "Serious": "NULL",
      "Total cases 1M": "0.1"
    },
    {
      "countryId": "340",
      "Country": "Honduras",
      "Total Cases": "2",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "2",
      "Serious": "NULL",
      "Total cases 1M": "0.2"
    },
    {
      "countryId": "388",
      "Country": "Jamaica",
      "Total Cases": "2",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "2",
      "Serious": "NULL",
      "Total cases 1M": "0.7"
    },
    {
      "countryId": "663",
      "Country": "Saint Martin",
      "Total Cases": "2",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "2",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "328",
      "Country": "Guyana",
      "Total Cases": "1",
      "New Cases": "NULL",
      "Total Deaths": "1",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "0",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "20",
      "Country": "Andorra",
      "Total Cases": "1",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "1",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "400",
      "Country": "Jordan",
      "Total Cases": "1",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "1",
      "Serious": "NULL",
      "Total cases 1M": "0.1"
    },
    {
      "countryId": "524",
      "Country": "Nepal",
      "Total Cases": "1",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "1",
      "Active Cases": "0",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "64",
      "Country": "Bhutan",
      "Total Cases": "1",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "1",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "384",
      "Country": "Ivory Coast",
      "Total Cases": "1",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "1",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "178",
      "Country": "DRC",
      "Total Cases": "1",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "1",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "NULL",
      "Country": "NULL",
      "Total Cases": "1",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "1",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "NULL",
      "Country": "Gibraltar",
      "Total Cases": "1",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "1",
      "Active Cases": "0",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "336",
      "Country": "Vatican City",
      "Total Cases": "1",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "1",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "496",
      "Country": "Mongolia",
      "Total Cases": "1",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "1",
      "Serious": "NULL",
      "Total cases 1M": "0.3"
    },
    {
      "countryId": "NULL",
      "Country": "NULL",
      "Total Cases": "1",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "1",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "NULL",
      "Country": "NULL",
      "Total Cases": "1",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "1",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    },
    {
      "countryId": "768",
      "Country": "Togo",
      "Total Cases": "1",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "1",
      "Serious": "NULL",
      "Total cases 1M": "0.1"
    },
    {
      "countryId": "780",
      "Country": "Trinidad and Tobago",
      "Total Cases": "1",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "1",
      "Serious": "NULL",
      "Total cases 1M": "0.7"
    },
    {
      "countryId": "792",
      "Country": "Turkey",
      "Total Cases": "1",
      "New Cases": "NULL",
      "Total Deaths": "NULL",
      "New Deaths": "NULL",
      "Total Recovered": "NULL",
      "Active Cases": "1",
      "Serious": "NULL",
      "Total cases 1M": "NULL"
    }
  ];
var dailyDeathData = [{'Date': 'Mar. 12', 'Daily Deaths': '354', 'Change in Daily': '22', 'Change in Daily %': '7%'}, {'Date': 'Mar. 11', 'Daily Deaths': '332', 'Change in Daily': '61', 'Change in Daily %': '23%'}, {'Date': 'Mar. 10', 'Daily Deaths': '271', 'Change in Daily': '73', 'Change in Daily %': '37%'}, {'Date': 'Mar. 9', 'Daily Deaths': '198', 'Change in Daily': '-30', 'Change in Daily %': '-13%'}, {'Date': 'Mar. 8', 'Daily Deaths': '228', 'Change in Daily': '123', 'Change in Daily %': '117%'}, {'Date': 'Mar. 7', 'Daily Deaths': '105', 'Change in Daily': '-2', 'Change in Daily %': '-2%'}, {'Date': 'Mar. 6', 'Daily Deaths': '107', 'Change in Daily': '5', 'Change in Daily %': '5%'}, {'Date': 'Mar. 5', 'Daily Deaths': '102', 'Change in Daily': '19', 'Change in Daily %': '23%'}, {'Date': 'Mar. 4', 'Daily Deaths': '83', 'Change in Daily': '-2', 'Change in Daily %': '-2%'}, {'Date': 'Mar. 3', 'Daily Deaths': '85', 'Change in Daily': '18', 'Change in Daily %': '27%'}, {'Date': 'Mar. 2', 'Daily Deaths': '67', 'Change in Daily': '-6', 'Change in Daily %': '-8%'}, {'Date': 'Mar. 1', 'Daily Deaths': '73', 'Change in Daily': '19', 'Change in Daily %': '35%'}, {'Date': 'Feb. 29', 'Daily Deaths': '54', 'Change in Daily': '-11', 'Change in Daily %': '-17%'}, {'Date': 'Feb. 28', 'Daily Deaths': '65', 'Change in Daily': '7', 'Change in Daily %': '12%'}, {'Date': 'Feb. 27', 'Daily Deaths': '58', 'Change in Daily': '21', 'Change in Daily %': '57%'}, {'Date': 'Feb. 26', 'Daily Deaths': '37', 'Change in Daily': '-27', 'Change in Daily %': '-42%'}, {'Date': 'Feb. 25', 'Daily Deaths': '64', 'Change in Daily': '-17', 'Change in Daily %': '-21%'}, {'Date': 'Feb. 24', 'Daily Deaths': '81', 'Change in Daily': '-77', 'Change in Daily %': '-49%'}, {'Date': 'Feb. 23', 'Daily Deaths': '158', 'Change in Daily': '58', 'Change in Daily %': '58%'}, {'Date': 'Feb. 22', 'Daily Deaths': '100', 'Change in Daily': '-13', 'Change in Daily %': '-12%'}, {'Date': 'Feb. 21', 'Daily Deaths': '113', 'Change in Daily': '-8', 'Change in Daily %': '-7%'}, {'Date': 'Feb. 20', 'Daily Deaths': '121', 'Change in Daily': '4', 'Change in Daily %': '3%'}, {'Date': 'Feb. 19', 'Daily Deaths': '117', 'Change in Daily': '-19', 'Change in Daily %': '-14%'}, {'Date': 'Feb. 18', 'Daily Deaths': '136', 'Change in Daily': '38', 'Change in Daily %': '39%'}, {'Date': 'Feb. 17', 'Daily Deaths': '98', 'Change in Daily': '-8', 'Change in Daily %': '-8%'}, {'Date': 'Feb. 16', 'Daily Deaths': '106', 'Change in Daily': '-37', 'Change in Daily %': '-26%'}, {'Date': 'Feb. 15', 'Daily Deaths': '143', 'Change in Daily': '0', 'Change in Daily %': '0%'}, {'Date': 'Feb. 14', 'Daily Deaths': '143', 'Change in Daily': '21', 'Change in Daily %': '17%'}, {'Date': 'Feb. 13', 'Daily Deaths': '122', 'Change in Daily': '-24', 'Change in Daily %': '-16%'}, {'Date': 'Feb. 12', 'Daily Deaths': '146', 'Change in Daily': '49', 'Change in Daily %': '51%'}, {'Date': 'Feb. 11', 'Daily Deaths': '97', 'Change in Daily': '-11', 'Change in Daily %': '-10%'}, {'Date': 'Feb. 10', 'Daily Deaths': '108', 'Change in Daily': '11', 'Change in Daily %': '11%'}, {'Date': 'Feb. 9', 'Daily Deaths': '97', 'Change in Daily': '8', 'Change in Daily %': '9%'}, {'Date': 'Feb. 8', 'Daily Deaths': '89', 'Change in Daily': '3', 'Change in Daily %': '3%'}, {'Date': 'Feb. 7', 'Daily Deaths': '86', 'Change in Daily': '13', 'Change in Daily %': '18%'}, {'Date': 'Feb. 6', 'Daily Deaths': '73', 'Change in Daily': '0', 'Change in Daily %': '0%'}, {'Date': 'Feb. 5', 'Daily Deaths': '73', 'Change in Daily': '7', 'Change in Daily %': '11%'}, {'Date': 'Feb. 4', 'Daily Deaths': '66', 'Change in Daily': '2', 'Change in Daily %': '3%'}, {'Date': 'Feb. 3', 'Daily Deaths': '64', 'Change in Daily': '6', 'Change in Daily %': '10%'}, {'Date': 'Feb. 2', 'Daily Deaths': '58', 'Change in Daily': '13', 'Change in Daily %': '29%'}, {'Date': 'Feb. 1', 'Daily Deaths': '45', 'Change in Daily': '-1', 'Change in Daily %': '-2%'}, {'Date': 'Jan. 31', 'Daily Deaths': '46', 'Change in Daily': '3', 'Change in Daily %': '7%'}, {'Date': 'Jan. 30', 'Daily Deaths': '43', 'Change in Daily': '5', 'Change in Daily %': '13%'}, {'Date': 'Jan. 29', 'Daily Deaths': '38', 'Change in Daily': '12', 'Change in Daily %': '46%'}, {'Date': 'Jan. 28', 'Daily Deaths': '26', 'Change in Daily': '0', 'Change in Daily %': '0%'}, {'Date': 'Jan. 27', 'Daily Deaths': '26', 'Change in Daily': '2', 'Change in Daily %': '8%'}, {'Date': 'Jan. 26', 'Daily Deaths': '24', 'Change in Daily': '9', 'Change in Daily %': '60%'}, {'Date': 'Jan. 25', 'Daily Deaths': '15', 'Change in Daily': '-1', 'Change in Daily %': '-6%'}, {'Date': 'Jan. 24', 'Daily Deaths': '16', 'Change in Daily': '8', 'Change in Daily %': '100%'}, {'Date': 'Jan. 23', 'Daily Deaths': '8', 'Change in Daily': '8', 'Change in Daily %': 'inf%'}]

var dailyTotalDeathData = [{'Date': 'Mar. 12', 'Total Deaths': '4982', 'Change in Total': '354', 'Change in Total %': '8%'}, {'Date': 'Mar. 11', 'Total Deaths': '4628', 'Change in Total': '332', 'Change in Total %': '8%'}, {'Date': 'Mar. 10', 'Total Deaths': '4296', 'Change in Total': '271', 'Change in Total %': '7%'}, {'Date': 'Mar. 9', 'Total Deaths': '4025', 'Change in Total': '198', 'Change in Total %': '5%'}, {'Date': 'Mar. 8', 'Total Deaths': '3827', 'Change in Total': '228', 'Change in Total %': '6%'}, {'Date': 'Mar. 7', 'Total Deaths': '3599', 'Change in Total': '105', 'Change in Total %': '3%'}, {'Date': 'Mar. 6', 'Total Deaths': '3494', 'Change in Total': '107', 'Change in Total %': '3%'}, {'Date': 'Mar. 5', 'Total Deaths': '3387', 'Change in Total': '102', 'Change in Total %': '3%'}, {'Date': 'Mar. 4', 'Total Deaths': '3285', 'Change in Total': '83', 'Change in Total %': '3%'}, {'Date': 'Mar. 3', 'Total Deaths': '3202', 'Change in Total': '85', 'Change in Total %': '3%'}, {'Date': 'Mar. 2', 'Total Deaths': '3117', 'Change in Total': '67', 'Change in Total %': '2%'}, {'Date': 'Mar. 1', 'Total Deaths': '3050', 'Change in Total': '73', 'Change in Total %': '2%'}, {'Date': 'Feb. 29', 'Total Deaths': '2977', 'Change in Total': '54', 'Change in Total %': '2%'}, {'Date': 'Feb. 28', 'Total Deaths': '2923', 'Change in Total': '65', 'Change in Total %': '2%'}, {'Date': 'Feb. 27', 'Total Deaths': '2858', 'Change in Total': '58', 'Change in Total %': '2%'}, {'Date': 'Feb. 26', 'Total Deaths': '2800', 'Change in Total': '37', 'Change in Total %': '1%'}, {'Date': 'Feb. 25', 'Total Deaths': '2763', 'Change in Total': '64', 'Change in Total %': '2%'}, {'Date': 'Feb. 24', 'Total Deaths': '2699', 'Change in Total': '81', 'Change in Total %': '3%'}, {'Date': 'Feb. 23', 'Total Deaths': '2618', 'Change in Total': '158', 'Change in Total %': '6%'}, {'Date': 'Feb. 22', 'Total Deaths': '2460', 'Change in Total': '100', 'Change in Total %': '4%'}, {'Date': 'Feb. 21', 'Total Deaths': '2360', 'Change in Total': '113', 'Change in Total %': '5%'}, {'Date': 'Feb. 20', 'Total Deaths': '2247', 'Change in Total': '121', 'Change in Total %': '6%'}, {'Date': 'Feb. 19', 'Total Deaths': '2126', 'Change in Total': '117', 'Change in Total %': '6%'}, {'Date': 'Feb. 18', 'Total Deaths': '2009', 'Change in Total': '136', 'Change in Total %': '7%'}, {'Date': 'Feb. 17', 'Total Deaths': '1873', 'Change in Total': '98', 'Change in Total %': '6%'}, {'Date': 'Feb. 16', 'Total Deaths': '1775', 'Change in Total': '106', 'Change in Total %': '6%'}, {'Date': 'Feb. 15', 'Total Deaths': '1669', 'Change in Total': '143', 'Change in Total %': '9%'}, {'Date': 'Feb. 14', 'Total Deaths': '1526', 'Change in Total': '143', 'Change in Total %': '10%'}, {'Date': 'Feb. 13', 'Total Deaths': '1383', 'Change in Total': '122', 'Change in Total %': '10%'}, {'Date': 'Feb. 12', 'Total Deaths': '1261', 'Change in Total': '146', 'Change in Total %': '13%'}, {'Date': 'Feb. 11', 'Total Deaths': '1115', 'Change in Total': '97', 'Change in Total %': '10%'}, {'Date': 'Feb. 10', 'Total Deaths': '1018', 'Change in Total': '108', 'Change in Total %': '12%'}, {'Date': 'Feb. 9', 'Total Deaths': '910', 'Change in Total': '97', 'Change in Total %': '12%'}, {'Date': 'Feb. 8', 'Total Deaths': '813', 'Change in Total': '89', 'Change in Total %': '12%'}, {'Date': 'Feb. 7', 'Total Deaths': '724', 'Change in Total': '86', 'Change in Total %': '13%'}, {'Date': 'Feb. 6', 'Total Deaths': '638', 'Change in Total': '73', 'Change in Total %': '13%'}, {'Date': 'Feb. 5', 'Total Deaths': '565', 'Change in Total': '73', 'Change in Total %': '15%'}, {'Date': 'Feb. 4', 'Total Deaths': '492', 'Change in Total': '66', 'Change in Total %': '15%'}, {'Date': 'Feb. 3', 'Total Deaths': '426', 'Change in Total': '64', 'Change in Total %': '18%'}, {'Date': 'Feb. 2', 'Total Deaths': '362', 'Change in Total': '58', 'Change in Total %': '19%'}, {'Date': 'Feb. 1', 'Total Deaths': '304', 'Change in Total': '45', 'Change in Total %': '17%'}, {'Date': 'Jan. 31', 'Total Deaths': '259', 'Change in Total': '46', 'Change in Total %': '22%'}, {'Date': 'Jan. 30', 'Total Deaths': '213', 'Change in Total': '43', 'Change in Total %': '25%'}, {'Date': 'Jan. 29', 'Total Deaths': '170', 'Change in Total': '38', 'Change in Total %': '29%'}, {'Date': 'Jan. 28', 'Total Deaths': '132', 'Change in Total': '26', 'Change in Total %': '25%'}, {'Date': 'Jan. 27', 'Total Deaths': '106', 'Change in Total': '26', 'Change in Total %': '33%'}, {'Date': 'Jan. 26', 'Total Deaths': '80', 'Change in Total': '24', 'Change in Total %': '43%'}, {'Date': 'Jan. 25', 'Total Deaths': '56', 'Change in Total': '15', 'Change in Total %': '37%'}, {'Date': 'Jan. 24', 'Total Deaths': '41', 'Change in Total': '16', 'Change in Total %': '64%'}, {'Date': 'Jan. 23', 'Total Deaths': '25', 'Change in Total': '8', 'Change in Total %': '47%'}]